server:
  port: 80
spring:
  # freemarker 配置
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html
    template-loader-path: classpath:/templates/
  # mail配置
  mail:
    host: smtp.qq.com
    port: 465
    username: *
    password: *
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true